name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |

      - name: Run unit tests
        run: 
          python.exe -m unittest triangle.py
          python.exe -m unittest circe.py
          python.exe -m unittest square.py
          python.exe -m unittest rectangle.py
          
